version: '3.8'

services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    command: server /data/ --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234

  nginx:
    image: nginx:alpine
    ports:
      - '5050:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
